const ROOTS = {
  ped: { definition: "foot or child", examples: ["orthopedist", "pedagogue", "centipede", "expedition", "pedestrian", "pedestal"] },
  mort: { definition: "death", examples: ["mortal", "mortician", "mortified", "immortality", "mortuary", "moribund"] },
  carn: { definition: "flesh", examples: ["carnivorous", "incarnate", "reincarnated", "carnival", "carnation", "carnage"] },
  psych: { definition: "soul", examples: ["psychology", "psychic", "psychopathic", "parapsychology", "psychosis"] },
  ethno: { definition: "race or culture", examples: ["ethnocentrism", "ethnic group", "ethnography", "ethnologist"] },
  gen: { definition: "origin", examples: ["genetics", "hydrogen", "progeny", "engender", "gene", "ingenuous", "indigenous"] },
  nat: { definition: "born", examples: ["prenatal", "native", "natural", "nativity", "nation", "nascent", "natal", "perinatal"] },
  paleo: { definition: "old", examples: ["paleozoic", "paleolithic", "paleontologist", "paleoanthropic", "paleography"] },
  curs: { definition: "run", examples: ["cursive", "discursive", "incursion", "precursor", "cursory", "cursorial", "cursor"] },
  crypt: { definition: "hidden", examples: ["cryptic", "cryptologist", "crypt", "cryptogram", "encrypt", "cryptesthesia"] },
  cad: { definition: "fall", examples: ["cascade", "cadaver", "cadence", "cadenza", "cadaverous", "decadent"] },
  capit: { definition: "head", examples: ["decapitate", "capital", "recapitulate", "capitulation", "capitulum"] },
  loqu: { definition: "talk", examples: ["loquacious", "circumlocution", "eloquent", "soliloquy", "somniloquy"] },
  sacro: { definition: "holy", examples: ["sacrosanct", "sacred", "sacrifice", "sacrament", "sacrilege", "consecrate"] },
  uni: { definition: "one", examples: ["unicycle", "universe", "united", "union", "uniform", "unison", "unique", "unicorn"] },
  ness: { definition: "quality", examples: ["softness", "redness", "politeness", "kindness", "darkness", "vagueness"] },
  alt: { definition: "high", examples: ["altitude", "alto", "altimeter", "altar", "altocumulus", "altiplano"] },
  ics: { definition: "art", examples: ["politics", "economics", "aesthetics", "graphics", "ethics", "calisthenics"] },
  iso: { definition: "equal", examples: ["isothermal", "isometric", "isosceles", "isomer", "isocracy", "isotope"] },
  vert: { definition: "turn", examples: ["convert", "revert", "inverted", "divert", "vertex", "controvert", "extrovert", "introvert"] },
  ate: { definition: "cause", examples: ["domesticate", "implicate", "create", "procreate", "insinuate", "placate", "dominate"] },
  cor: { definition: "heart", examples: ["core", "concord", "discord", "misericord", "cordial", "courageous"] },
  ess: { definition: "female", examples: ["lioness", "empress", "princess", "baroness", "seamstress", "governess"] },
  muta: { definition: "change", examples: ["mutant", "mutation", "mutagenic", "mutable", "transmutation", "immutable"] },
  fug: { definition: "flee", examples: ["centrifuge", "fugitive", "tempus fugit", "subterfuge", "refugee", "fugue"] }
};
